### PR TITLE
Add sink resource

### LINKED ISSUE #37: Add sink support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

App `pulsar_sink` to terraform-provider-pulsar, which supports create, remove, import and update the sink resource.

### New or Affected Resource(s)

* pulsar_sink

### In Progress

#38

### PR DESCRIPTION
**Pull request by nodece**
Fix #37

### TODO
- [x] Add description for sink resource
- [x] Update README.md

### CODE REVIEW

**Comment by sijie** [comment]
@nlu90 @freeznet Can you review this PR?

**Review by nlu90 — COMMENTED** [review]
The code itself looks fine. 

Is there any guidance on how to actually run it?

**Comment by nodece** [comment]
@nlu90 Currently, we only have README.md, you can check out the `Installation` and `Example` sections. When you clone this PR to local, you need to run `make build-dev` to install this plugin.

**Comment by nlu90** [comment]
Seems my local env lacks of some dependency. 
```
│ Error: open testdata/pulsar-io/pulsar-io-jdbc-postgres-2.8.1.nar: no such file or directory
│
│   with pulsar_sink.sink-1,
│   on main.tf line 33, in resource "pulsar_sink" "sink-1":
│   33: resource "pulsar_sink" "sink-1" {
│
╵
```

Did you test the sink can be submitted correctly?

**Comment by nodece** [comment]
@nlu90 Good catch, `pulsar-io-jdbc-postgres-2.8.1.nar` has been added to examples.

**Comment by nlu90** [comment]
1.  I don't think we should commit the binary file `pulsar-io-jdbc-postgres-2.8.1.nar` into the repo. It's better to have some instructions on where to download it and how to set it up.

2. I got the following issues when trying again by running `terraform init`:

```
╷
│ Error: Failed to install provider
│
│ Error while installing apache/pulsar v1.0.0: the local package for registry.terraform.io/apache/pulsar 1.0.0 doesn't match any of the checksums previously recorded in
│ the dependency lock file (this might be because the available checksums are for packages targeting different platforms)
╵
```

**Comment by nodece** [comment]
@nlu90 I fix the above issues, you can use the following script to test this:
```shell
gh repo clone https://github.com/streamnative/terraform-provider-pulsar
cd terraform-provider-pulsar
gh pr checkout 38
make build-dev
cd examples/sinks/
terraform init
terraform apply
```

**Review by maxsxu — APPROVED** [review]

**Pull request merged**
